// Mock data for the FOODCAST application
export interface Product {
  id: string;
  name: string;
  description: string;
  category: string;
  emoji: string;
  image: string;
  currentPrice: number;
  predictedPrice: number;
  previousPrice: number;
  volume: string;
  sentiment: "Bullish" | "Bearish" | "Neutral";
  sparklineData: { value: number }[];
  forecastData: {
    name: string;
    actual: number | null;
    predicted: number | null;
  }[];
}

export const products: Product[] = [
  {
    id: "premium-rice",
    name: "Premium Rice",
    description: "A staple grain in Filipino households, premium rice is the most consumed food commodity in the NCR. Prices are influenced by importation policies, harvest seasons, and global supply chain trends.",
    category: "Grains",
    emoji: "🍚",
    image: "/products/premium-rice.png",
    currentPrice: 52.5,
    predictedPrice: 54.8,
    previousPrice: 50.2,
    volume: "12,450 kg",
    sentiment: "Bullish",
    sparklineData: [
      { value: 48 },
      { value: 49 },
      { value: 50 },
      { value: 49.5 },
      { value: 51 },
      { value: 50.2 },
      { value: 52.5 },
    ],
    forecastData: [
      { name: "Jan", actual: 48, predicted: null },
      { name: "Feb", actual: 49, predicted: null },
      { name: "Mar", actual: 50, predicted: null },
      { name: "Apr", actual: 49.5, predicted: null },
      { name: "May", actual: 51, predicted: 51 },
      { name: "Jun", actual: null, predicted: 52.5 },
      { name: "Jul", actual: null, predicted: 53.8 },
      { name: "Aug", actual: null, predicted: 54.8 },
    ],
  },
  {
    id: "red-onion",
    name: "Red Onion",
    description: "A key cooking ingredient across Filipino cuisine, red onion prices are highly volatile and sensitive to local harvest yields, weather disruptions, and import regulations in the NCR.",
    category: "Vegetables",
    emoji: "🧅",
    image: "/products/red-onion.png",
    currentPrice: 180.0,
    predictedPrice: 165.5,
    previousPrice: 195.0,
    volume: "8,320 kg",
    sentiment: "Bearish",
    sparklineData: [
      { value: 210 },
      { value: 205 },
      { value: 195 },
      { value: 190 },
      { value: 185 },
      { value: 182 },
      { value: 180 },
    ],
    forecastData: [
      { name: "Jan", actual: 210, predicted: null },
      { name: "Feb", actual: 205, predicted: null },
      { name: "Mar", actual: 195, predicted: null },
      { name: "Apr", actual: 190, predicted: null },
      { name: "May", actual: 185, predicted: 185 },
      { name: "Jun", actual: null, predicted: 175 },
      { name: "Jul", actual: null, predicted: 170 },
      { name: "Aug", actual: null, predicted: 165.5 },
    ],
  },
  {
    id: "tomato",
    name: "Tomato",
    description: "Widely used in Filipino dishes like sinigang and adobo, tomatoes experience seasonal price swings driven by typhoon damage, dry spells, and transportation costs from major growing regions.",
    category: "Vegetables",
    emoji: "🍅",
    image: "/products/tomato.png",
    currentPrice: 85.0,
    predictedPrice: 92.3,
    previousPrice: 78.0,
    volume: "6,150 kg",
    sentiment: "Bullish",
    sparklineData: [
      { value: 70 },
      { value: 72 },
      { value: 75 },
      { value: 78 },
      { value: 80 },
      { value: 82 },
      { value: 85 },
    ],
    forecastData: [
      { name: "Jan", actual: 70, predicted: null },
      { name: "Feb", actual: 72, predicted: null },
      { name: "Mar", actual: 75, predicted: null },
      { name: "Apr", actual: 78, predicted: null },
      { name: "May", actual: 80, predicted: 80 },
      { name: "Jun", actual: null, predicted: 85 },
      { name: "Jul", actual: null, predicted: 89 },
      { name: "Aug", actual: null, predicted: 92.3 },
    ],
  },
  {
    id: "galunggong",
    name: "Galunggong",
    description: "Known as the 'poor man's fish,' galunggong is one of the most affordable and widely consumed fish in the Philippines. Its price serves as an economic indicator for lower-income food accessibility.",
    category: "Fishery",
    emoji: "🐟",
    image: "/products/galunggong.png",
    currentPrice: 220.0,
    predictedPrice: 215.0,
    previousPrice: 225.0,
    volume: "4,890 kg",
    sentiment: "Bearish",
    sparklineData: [
      { value: 230 },
      { value: 228 },
      { value: 225 },
      { value: 223 },
      { value: 222 },
      { value: 221 },
      { value: 220 },
    ],
    forecastData: [
      { name: "Jan", actual: 230, predicted: null },
      { name: "Feb", actual: 228, predicted: null },
      { name: "Mar", actual: 225, predicted: null },
      { name: "Apr", actual: 223, predicted: null },
      { name: "May", actual: 222, predicted: 222 },
      { name: "Jun", actual: null, predicted: 219 },
      { name: "Jul", actual: null, predicted: 217 },
      { name: "Aug", actual: null, predicted: 215 },
    ],
  },
  {
    id: "cabbage",
    name: "Cabbage",
    description: "Primarily sourced from highland farms in Benguet and Mountain Province, cabbage prices in the NCR are affected by weather conditions in northern Luzon and transport logistics.",
    category: "Vegetables",
    emoji: "🥬",
    image: "/products/cabbage.png",
    currentPrice: 60.0,
    predictedPrice: 58.5,
    previousPrice: 62.0,
    volume: "5,200 kg",
    sentiment: "Neutral",
    sparklineData: [
      { value: 65 },
      { value: 63 },
      { value: 62 },
      { value: 61 },
      { value: 60 },
      { value: 60.5 },
      { value: 60 },
    ],
    forecastData: [
      { name: "Jan", actual: 65, predicted: null },
      { name: "Feb", actual: 63, predicted: null },
      { name: "Mar", actual: 62, predicted: null },
      { name: "Apr", actual: 61, predicted: null },
      { name: "May", actual: 60, predicted: 60 },
      { name: "Jun", actual: null, predicted: 59.5 },
      { name: "Jul", actual: null, predicted: 59 },
      { name: "Aug", actual: null, predicted: 58.5 },
    ],
  },
  {
    id: "garlic",
    name: "Garlic",
    description: "An essential spice in Filipino cooking, most garlic consumed in the NCR is imported. Prices are driven by international trade policies, tariffs, and seasonal demand spikes.",
    category: "Spices",
    emoji: "🧄",
    image: "/products/garlic.png",
    currentPrice: 145.0,
    predictedPrice: 152.0,
    previousPrice: 140.0,
    volume: "3,800 kg",
    sentiment: "Bullish",
    sparklineData: [
      { value: 130 },
      { value: 133 },
      { value: 135 },
      { value: 138 },
      { value: 140 },
      { value: 142 },
      { value: 145 },
    ],
    forecastData: [
      { name: "Jan", actual: 130, predicted: null },
      { name: "Feb", actual: 133, predicted: null },
      { name: "Mar", actual: 135, predicted: null },
      { name: "Apr", actual: 138, predicted: null },
      { name: "May", actual: 140, predicted: 140 },
      { name: "Jun", actual: null, predicted: 145 },
      { name: "Jul", actual: null, predicted: 149 },
      { name: "Aug", actual: null, predicted: 152 },
    ],
  },
  {
    id: "tilapia",
    name: "Tilapia",
    description: "A popular freshwater fish farmed extensively in Central Luzon and Calabarzon. Tilapia is a protein staple for many Filipino families, with prices affected by feed costs and aquaculture output.",
    category: "Fishery",
    emoji: "🐠",
    image: "/products/tilapia.png",
    currentPrice: 160.0,
    predictedPrice: 158.0,
    previousPrice: 162.0,
    volume: "7,100 kg",
    sentiment: "Neutral",
    sparklineData: [
      { value: 165 },
      { value: 163 },
      { value: 162 },
      { value: 161 },
      { value: 160 },
      { value: 160.5 },
      { value: 160 },
    ],
    forecastData: [
      { name: "Jan", actual: 165, predicted: null },
      { name: "Feb", actual: 163, predicted: null },
      { name: "Mar", actual: 162, predicted: null },
      { name: "Apr", actual: 161, predicted: null },
      { name: "May", actual: 160, predicted: 160 },
      { name: "Jun", actual: null, predicted: 159 },
      { name: "Jul", actual: null, predicted: 158.5 },
      { name: "Aug", actual: null, predicted: 158 },
    ],
  },
  {
    id: "eggplant",
    name: "Eggplant",
    description: "A versatile vegetable commonly used in tortang talong and pinakbet. Eggplant is grown year-round in the Philippines, but prices fluctuate with monsoon seasons and pest infestations.",
    category: "Vegetables",
    emoji: "🍆",
    image: "/products/eggplant.png",
    currentPrice: 75.0,
    predictedPrice: 80.0,
    previousPrice: 70.0,
    volume: "4,500 kg",
    sentiment: "Bullish",
    sparklineData: [
      { value: 65 },
      { value: 67 },
      { value: 68 },
      { value: 70 },
      { value: 72 },
      { value: 73 },
      { value: 75 },
    ],
    forecastData: [
      { name: "Jan", actual: 65, predicted: null },
      { name: "Feb", actual: 67, predicted: null },
      { name: "Mar", actual: 68, predicted: null },
      { name: "Apr", actual: 70, predicted: null },
      { name: "May", actual: 72, predicted: 72 },
      { name: "Jun", actual: null, predicted: 75 },
      { name: "Jul", actual: null, predicted: 78 },
      { name: "Aug", actual: null, predicted: 80 },
    ],
  },
  {
    id: "bangus",
    name: "Bangus",
    description: "The national fish of the Philippines, bangus (milkfish) is farmed in fishponds and pens across the country. Prices are influenced by feed costs, weather patterns, and holiday demand surges.",
    category: "Fishery",
    emoji: "🐟",
    image: "/products/bangus.png",
    currentPrice: 195.0,
    predictedPrice: 200.0,
    previousPrice: 190.0,
    volume: "5,600 kg",
    sentiment: "Bullish",
    sparklineData: [
      { value: 180 },
      { value: 183 },
      { value: 185 },
      { value: 188 },
      { value: 190 },
      { value: 192 },
      { value: 195 },
    ],
    forecastData: [
      { name: "Jan", actual: 180, predicted: null },
      { name: "Feb", actual: 183, predicted: null },
      { name: "Mar", actual: 185, predicted: null },
      { name: "Apr", actual: 188, predicted: null },
      { name: "May", actual: 190, predicted: 190 },
      { name: "Jun", actual: null, predicted: 195 },
      { name: "Jul", actual: null, predicted: 198 },
      { name: "Aug", actual: null, predicted: 200 },
    ],
  },
];

export const categories = ["All", "Grains", "Vegetables", "Fishery", "Spices"];
